In [4]:

# ==========================================
# R PROGRAMMING - WEEK 7
# LISTS
# ==========================================

# 1. Create two matrices
x1 <- matrix(
  c(1, 2, 3, 4),
  nrow = 2,
  ncol = 2,
  byrow = TRUE
)

x2 <- matrix(
  c(5, 6, 7, 8),
  nrow = 2,
  ncol = 2,
  byrow = TRUE
)

x1
x2


# 2. Create a list containing matrices
matlist <- list(x1, x2)

matlist


# 3. Access first list element
matlist[1]


# 4. Access second list element
matlist[2]


# 5. Access actual matrix from first element
matlist[[1]]


# 6. Access actual matrix from second element
matlist[[2]]


# 7. Create list with different object types
z1 <- list(
  c("water", "juice", "lemonade"),
  rep(1:4, each = 2),
  matrix(
    data = 5:8,
    nrow = 2,
    ncol = 2,
    byrow = TRUE
  )
)

z1


# 8. Access first element
z1[[1]]


# 9. Access second element
z1[[2]]


# 10. Access third element
z1[[3]]


# 11. Access a specific value
z1[[1]][2]


# 12. Create named list
list2 <- list(
  drink1 = "water",
  drink2 = "juice",
  drink3 = "lemonade",
  drink4 = "tea",
  drink5 = "coffee",
  drink6 = "milk"
)

list2


# 13. Display names
names(list2)


# 14. Access using name
list2$drink1


# 15. Access using [[ ]]
list2[["drink2"]]


# 16. Access multiple elements
list2[1:3]


# 17. Add new element
list2$drink7 <- "smoothie"

list2


# 18. Remove element
list2$drink7 <- NULL

list2


# ==========================================
# DATE SEQUENCES
# ==========================================

# Days
seq(
  as.Date("2025-01-01"),
  by = "days",
  length = 6
)

# Months
seq(
  as.Date("2025-01-01"),
  by = "months",
  length = 6
)

# Years
seq(
  as.Date("2020-01-01"),
  by = "years",
  length = 6
)


# ==========================================
# ALPHABET SEQUENCES
# ==========================================

letters

letters[1:5]

letters[5:1]

LETTERS

LETTERS[1:5]

LETTERS[5:1]

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

[1] "water"    "juice"    "lemonade"

[1] 1 1 2 2 3 3 4 4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

[1] "juice"

$drink1
[1] "water"

$drink2
[1] "juice"

$drink3
[1] "lemonade"

$drink4
[1] "tea"

$drink5
[1] "coffee"

$drink6
[1] "milk"

[1] "drink1" "drink2" "drink3" "drink4" "drink5" "drink6"

[1] "water"

[1] "juice"

$drink1
[1] "water"

$drink2
[1] "juice"

$drink3
[1] "lemonade"

$drink1
[1] "water"

$drink2
[1] "juice"

$drink3
[1] "lemonade"

$drink4
[1] "tea"

$drink5
[1] "coffee"

$drink6
[1] "milk"

$drink7
[1] "smoothie"

$drink1
[1] "water"

$drink2
[1] "juice"

$drink3
[1] "lemonade"

$drink4
[1] "tea"

$drink5
[1] "coffee"

$drink6
[1] "milk"

[1] "2025-01-01" "2025-01-02" "2025-01-03" "2025-01-04" "2025-01-05"
[6] "2025-01-06"

[1] "2025-01-01" "2025-02-01" "2025-03-01" "2025-04-01" "2025-05-01"
[6] "2025-06-01"

[1] "2020-01-01" "2021-01-01" "2022-01-01" "2023-01-01" "2024-01-01"
[6] "2025-01-01"

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "a" "b" "c" "d" "e"

[1] "e" "d" "c" "b" "a"

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C" "D" "E"

[1] "E" "D" "C" "B" "A"